on:
  workflow_call: 
    inputs:
      
      runs-on:
        type: string
        description: 'Runs on'

      gitops-helm-chart-path:
        required: true
        type: string
        description: 'Gitops helm chart path'

      build-docker-context-path:
        required: true
        type: string
        description: 'Docker context path'

      build-docker-file-path:
        required: true
        type: string
        description: 'Dockerfile path'

      docker-server:
        required: true
        type: string
        description: 'Docker registry server'

      docker-repository:
        required: true
        type: string
        description: 'Docker repository name'

      docker-tag-prefix:
        required: false
        default: ''
        type: string
        description: 'Docker tag prefix'

      docker-build-only:
        required: false
        default: false
        type: boolean
        description: 'Docker build only'

    secrets:
      docker-username:
        required: true
        description: 'Docker username for login to docker registry'
      docker-password:
        required: true
        description: 'Docker password for login to docker registry'

    outputs:
      GIT_COMMIT_ID:
        value: ${{ jobs.build_and_push.outputs.GIT_COMMIT_ID }}
      GIT_COMMIT_MSG:
        value: ${{ jobs.build_and_push.outputs.GIT_COMMIT_MSG }}
      GIT_COMITTER:
        value: ${{ jobs.build_and_push.outputs.GIT_COMITTER }}
      GIT_COMMIT_DATE:
        value: ${{ jobs.build_and_push.outputs.GIT_COMMIT_DATE }}
      DOCKER_REPO:
        value: ${{ jobs.build_and_push.outputs.DOCKER_REPO }}
      DOCKER_TAG:
        value: ${{ jobs.build_and_push.outputs.DOCKER_TAG }}
      REV_DATE:
        value: ${{ jobs.build_and_push.outputs.REV_DATE }}
      REV_UNIQUE:
        value: ${{ jobs.build_and_push.outputs.REV_UNIQUE }}

jobs:
  build_and_push:
    uses: btungut-phonestore/devops/.github/workflows/workflow-docker-build-push.yml@master
    with:
      runs-on: ${{ inputs.runs-on }}
      build-docker-context-path: ${{ inputs.build-docker-context-path }}
      build-docker-file-path: ${{ inputs.build-docker-file-path }}
      docker-server: ${{ inputs.docker-server }}
      docker-repository: ${{ inputs.docker-repository }}
      docker-tag-prefix: ${{ inputs.docker-tag-prefix }}
      docker-build-only: ${{ inputs.docker-build-only }}
    secrets:
      docker-username: ${{ secrets.docker-username }}
      docker-password: ${{ secrets.docker-password }}

  helm_upgrade:
    needs: build_and_push
    runs-on: ${{ inputs.runs-on }}
    steps: 
      - uses: btungut-phonestore/devops/.github/actions/common@master
        id: common-vars

      - uses: btungut-phonestore/devops/.github/actions/git-checkout@master
        with:
          gitToken: ${{ secrets.GITHUB_TOKEN }}
          checkoutGitOps: true
          gitOpsBranch: 'dev'

      - name: update values.yaml
        shell: bash
        run: |
          set -euo pipefail
          
          CHART_DIR="${{ inputs.gitops-helm-chart-path }}"
          [ -d "${CHART_DIR}" ] || { echo "Directory ${CHART_DIR} does not exist"; exit 1; }
          pushd "${CHART_DIR}"
          tree .

          [ -f "values.yaml" ] || { echo "File values.yaml does not exist in $PWD"; exit 1; }
          [ -f "Chart.yaml" ] || { echo "File Chart.yaml does not exist in $PWD"; exit 1; }

          CHART_VERSION=`yq '.version' Chart.yaml`
          ARR=(${CHART_VERSION//./ })
          CURRENT_CHART_VERSION="${ARR[0]}.${ARR[1]}.${ARR[2]%%-*}-${{ steps.common-vars.outputs.rev-name }}"
          ${{ github.workspace }}/devops/scripts/modify-yaml.sh Chart.yaml ".version" "${CURRENT_CHART_VERSION}" "${{ job.build_and_push.outputs.GIT_COMMIT_ID }}"
          ${{ github.workspace }}/devops/scripts/modify-yaml.sh Chart.yaml ".appVersion" "${{ job.build_and_push.outputs.GIT_COMMIT_ID }} (${{ job.build_and_push.outputs.GIT_COMITTER }})"
          ${{ github.workspace }}/devops/scripts/modify-yaml.sh Chart.yaml ".description" "${{ job.build_and_push.outputs.GIT_COMMIT_MSG }}"
          ${{ github.workspace }}/devops/scripts/modify-yaml.sh values.yaml ".deployment.image.repository" "${{ job.build_and_push.outputs.DOCKER_REPO }}"
          ${{ github.workspace }}/devops/scripts/modify-yaml.sh values.yaml ".deployment.image.tag" "${{ job.build_and_push.outputs.DOCKER_TAG }}"

          cat Chart.yaml
          echo "----------------"
          cat values.yaml

        working-directory: gitops